public class Util {

    public static final String LOAN_APPLICATION_PREPARE_DOCUMENT = 'Prepare Document';
    public static final String TYPE_LOAN_APPLICATION = 'Loan Application';
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_SUBMITTED = 'Submitted';
    public static final String STATUS_REJECTED = 'Rejected';
    public static final String STATUS_DRAFT = 'Draft';

    public static final String LOAN_APP_REJECTION_REASON = 'Borrower does not meet the product minimum credit score.';

}
